name: Java CI with Gradle

on:
  push:
    branches-ignore:
      - main

jobs:
  build:
    name: Continuous Integration
    runs-on: ubuntu-latest
    permissions:
      contents: read

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Setup MySQL
        uses: mirromutth/mysql-action@v1.1
        with:
          mysql database: 'testDB'
          mysql user: 'test'
          mysql password: 'testPW'

      - name: Create application.properties
        run: |
          cat <<EOT > ./src/main/resources/application.properties
          spring.application.name=WithU
          
          spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
          spring.jpa.database=mysql
          spring.jpa.show-sql=true
          spring.jpa.properties.hibernate.format_sql=true
          commit.hash=local
          api.server.url=http://localhost:8080
          
          # S3
          cloud.aws.credentials.accessKey=${{ secrets.AWS_ACCESS_KEY_ID }}
          cloud.aws.credentials.secretKey=${{ secrets.AWS_SECRET_ACCESS_KEY }}
          cloud.aws.s3.bucket=${{ secrets.AWS_BUCKET_NAME }}
          cloud.aws.s3.bucket-path=${{ secrets.AWS_BUCKET_PATH }}
               
          # JWT Secret
          spring.jwt.secret=${{ secrets.JWT_SECRET }}

          # Kakao OAuth2 Configuration
          spring.security.oauth2.client.registration.kakao.client-name=${{ secrets.KAKAO_CLIENT_NAME }}
          spring.security.oauth2.client.registration.kakao.client-id=${{ secrets.KAKAO_CLIENT_ID }}
          spring.security.oauth2.client.registration.kakao.client-secret=${{ secrets.KAKAO_CLIENT_SECRET }}
          spring.security.oauth2.client.registration.kakao.redirect-uri=${{ secrets.KAKAO_REDIRECT_URI }}
          spring.security.oauth2.client.registration.kakao.authorization-grant-type=${{ secrets.KAKAO_AUTH_GRANT_TYPE }}
          spring.security.oauth2.client.registration.kakao.client-authentication-method=${{ secrets.KAKAO_AUTH_METHOD }}
          spring.security.oauth2.client.registration.kakao.scope=${{ secrets.KAKAO_SCOPE }}

          spring.security.oauth2.client.provider.kakao.authorization-uri=${{ secrets.KAKAO_AUTHORIZATION_URI }}
          spring.security.oauth2.client.provider.kakao.token-uri=${{ secrets.KAKAO_TOKEN_URI }}
          spring.security.oauth2.client.provider.kakao.user-info-uri=${{ secrets.KAKAO_USER_INFO_URI }}
          spring.security.oauth2.client.provider.kakao.user-name-attribute=${{ secrets.KAKAO_USER_NAME_ATTRIBUTE }}

          EOT
        shell: bash

      - name: Generate test-application.properties
        run: |
          echo "cloud.aws.credentials.accessKey=${{ secrets.AWS_ACCESS_KEY_ID }}" >> ./src/test/resources/application.properties
          echo "cloud.aws.credentials.secretKey=${{ secrets.AWS_SECRET_ACCESS_KEY }}" >> ./src/test/resources/application.properties
          echo "cloud.aws.s3.bucket=${{ secrets.AWS_BUCKET_NAME }}" >> ./src/test/resources/application.properties
          echo "cloud.aws.s3.bucket-path=${{ secrets.AWS_BUCKET_PATH }}" >> ./src/test/resources/application.properties
          
          echo "spring.jwt.secret=${{ secrets.JWT_SECRET }}" >> ./src/test/resources/application.properties
  
          echo "spring.security.oauth2.client.registration.kakao.client-name=${{ secrets.KAKAO_CLIENT_NAME }}" >> ./src/test/resources/application.properties
          echo "spring.security.oauth2.client.registration.kakao.client-id=${{ secrets.KAKAO_CLIENT_ID }}" >> ./src/test/resources/application.properties
          echo "spring.security.oauth2.client.registration.kakao.client-secret=${{ secrets.KAKAO_CLIENT_SECRET }}" >> ./src/test/resources/application.properties
          echo "spring.security.oauth2.client.registration.kakao.redirect-uri=${{ secrets.KAKAO_REDIRECT_URI }}" >> ./src/test/resources/application.properties
          echo "spring.security.oauth2.client.registration.kakao.authorization-grant-type=${{ secrets.KAKAO_AUTH_GRANT_TYPE }}" >> ./src/test/resources/application.properties
          echo "spring.security.oauth2.client.registration.kakao.client-authentication-method=${{ secrets.KAKAO_AUTH_METHOD }}" >> ./src/test/resources/application.properties
          echo "spring.security.oauth2.client.registration.kakao.scope=${{ secrets.KAKAO_SCOPE }}" >> ./src/test/resources/application.properties
          
          echo "spring.security.oauth2.client.provider.kakao.authorization-uri=${{ secrets.KAKAO_AUTHORIZATION_URI }}" >> ./src/test/resources/application.properties
          echo "spring.security.oauth2.client.provider.kakao.token-uri=${{ secrets.KAKAO_TOKEN_URI }}" >> ./src/test/resources/application.properties
          echo "spring.security.oauth2.client.provider.kakao.user-info-uri=${{ secrets.KAKAO_USER_INFO_URI }}" >> ./src/test/resources/application.properties
          echo "spring.security.oauth2.client.provider.kakao.user-name-attribute=${{ secrets.KAKAO_USER_NAME_ATTRIBUTE }}" >> ./src/test/resources/application.properties

          echo "front-url=http://localhost:8080" >> ./src/test/resources/application.properties
          echo "redirect-url-suffix=/api/users/home" >> ./src/test/resources/application.properties

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@417ae3ccd767c252f5661f1ace9f835f9654f2b5 # v 3.1.0

      - name: Get short SHA
        id: slug
        run: echo "sha7=$(echo ${GITHUB_SHA} | cut -c1-7)" >> $GITHUB_OUTPUT

      - name: Grant execute permission for gradlew
        run: chmod +x ./gradlew

      - name: Run Spotless Apply
        run: ./gradlew spotlessApply

      - name: Build with Gradle Wrapper
        run: ./gradlew build
